# Generated by Django 4.2.1 on 2023-06-01 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Word',
        ),
    ]
