# Generated by Django 4.2.1 on 2023-06-01 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transactions', '0002_delete_word'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('date', models.DateTimeField()),
                ('payee', models.CharField(max_length=150)),
                ('source', models.CharField(choices=[('CH', 'Chase'), ('CO', 'Capital One'), ('HB', 'HEB'), ('OT', 'Other')], default='CH', max_length=2)),
                ('category', models.CharField(choices=[('RC', 'Recurring'), ('FD', 'Food'), ('GR', 'Groceries'), ('CL', 'Clothing'), ('OT', 'Other'), ('VC', 'Vacation'), ('GS', 'Gas'), ('CR', 'Car'), ('NA', 'N/A'), ('MD', 'Medical'), ('UT', 'Utilities'), ('CS', 'Counseling'), ('MG', 'Mortgage'), ('IC', 'Income'), ('SV', 'Savings'), ('TI', 'Tithe')], default='OT', max_length=2)),
            ],
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.UniqueConstraint(fields=('date', 'payee', 'amount'), name='unique_transaction'),
        ),
    ]
