# Generated by Django 4.2.1 on 2023-06-01 20:12

from django.db import migrations, models
from proj.transactions.models import Transaction

def extract_month(apps, schema_editor):

    for obj in Transaction.objects.all():
        month = obj.date.strftime('%B').upper()
        setattr(obj, 'budget_month', getattr(Transaction.BudgetMonthChoices, month))
        obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='budget_month',
            field=models.CharField(choices=[('JAN', 'January'), ('FEB', 'February'), ('MAR', 'March'), ('APR', 'April'), ('MAY', 'May'), ('JUN', 'June'), ('JUL', 'July'), ('AUG', 'August'), ('SEP', 'September'), ('OCT', 'October'), ('NOV', 'November'), ('DEC', 'December')], default='JAN', max_length=3),
        ),
        migrations.RunPython(extract_month),
    ]
