# Generated by Django 4.2.1 on 2023-06-08 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0007_envelope'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envelope',
            name='name',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
