# Generated by Django 4.2.1 on 2023-06-12 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0009_month_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='temp_budget_month',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='transactions.month'),
        ),
        migrations.AlterField(
            model_name='month',
            name='year',
            field=models.IntegerField(default=2023),
        ),
    ]
