from proj.transactions.models import Transaction as TX

TX_TO_CATEGORY = {
    "NYTimes": TX.TXCategories.RECURRING,
    "Easy Tiger": TX.TXCategories.FOOD,
    "Doordash": TX.TXCategories.FOOD,
    "H-E-B": TX.TXCategories.GROCERY,
    "HEB": TX.TXCategories.GROCERY,
    "its organic": TX.TXCategories.GROCERY,
    "Poshmark": TX.TXCategories.CLOTHING,
    "Apple": TX.TXCategories.RECURRING,
    "AMZN": TX.TXCategories.OTHER,
    "farmbox delivery": TX.TXCategories.GROCERY,
    "central market": TX.TXCategories.GROCERY,
    "black star": TX.TXCategories.FOOD,
    "Southwes": TX.TXCategories.VACATION,
    "Honest marys": TX.TXCategories.FOOD,
    "Cabo Bobs": TX.TXCategories.FOOD,
    "disneyplus": TX.TXCategories.RECURRING,
    "peloton": TX.TXCategories.RECURRING,
    "ATT*Bill": TX.TXCategories.UTILITIES,
    "Sunrise citgo mini mart": TX.TXCategories.OTHER,
    "celis": TX.TXCategories.FOOD,
    "barrett?s": TX.TXCategories.FOOD,
    "cava": TX.TXCategories.FOOD,
    "shell oil": TX.TXCategories.GAS,
    "American eagle": TX.TXCategories.CLOTHING,
    "turnstile": TX.TXCategories.FOOD,
    "turo": TX.TXCategories.VACATION,
    "o'reilly auto parts": TX.TXCategories.CAR,
    "modern market": TX.TXCategories.FOOD,
    "enchiladas-y-mas": TX.TXCategories.FOOD,
    "spotify": TX.TXCategories.RECURRING,
    "automatic payment": TX.TXCategories.EXCLUDED,
    "fresh plus": TX.TXCategories.GROCERY,
    "fwb hancock": TX.TXCategories.FOOD,
    "vuori": TX.TXCategories.CLOTHING,
    "american ai": TX.TXCategories.VACATION,
    "titayas": TX.TXCategories.FOOD,
    "central machine work": TX.TXCategories.FOOD,
    "lazarus brewing": TX.TXCategories.FOOD,
    "nervous charlies": TX.TXCategories.FOOD,
    "trader joe": TX.TXCategories.GROCERY,
    "peached tortilla": TX.TXCategories.FOOD,
    "that burger": TX.TXCategories.FOOD,
    "BROTZMAN SPORTS MEDICINE": TX.TXCategories.MEDICAL,
    "Jack allens kitchen": TX.TXCategories.FOOD,
    "airbnb": TX.TXCategories.VACATION,
    "buddys burgers": TX.TXCategories.VACATION,
    "SHELLEY GAUNTT MOELLER": TX.TXCategories.COUNSELING,
    "marine layer": TX.TXCategories.CLOTHING,
    "disney plus": TX.TXCategories.RECURRING,
    "tylers": TX.TXCategories.CLOTHING,
    "state farm insurance": TX.TXCategories.RECURRING,
    "lululemon": TX.TXCategories.CLOTHING,
    "chick-fil-a": TX.TXCategories.FOOD,
    "going.com": TX.TXCategories.RECURRING,
    "progressive ins": TX.TXCategories.RECURRING,
    "VERACRUZALLNATURA.COM": TX.TXCategories.FOOD,
    "epoch coffee": TX.TXCategories.FOOD,
    "CHASE CREDIT CRD AUTOPAY": TX.TXCategories.EXCLUDED,
    "CRESTVIEW RESIDE Assn Dues": TX.TXCategories.MORTGAGE,
    "SCHWAB BROKERAGE MONEYLINK": TX.TXCategories.SAVINGS,
    "NCR CORPORATION PAYROLL": TX.TXCategories.INCOME,
    "City of Austin T": TX.TXCategories.UTILITIES,
    "Reformed Uni": TX.TXCategories.TITHE,
    "ONE GAS TEXAS": TX.TXCategories.UTILITIES,
    "ROUNDPOINT": TX.TXCategories.MORTGAGE,
}